# permissions for end users to edit sonarqubes.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonarqube-editor-role
rules:
- apiGroups:
  - redhatgov.io
  resources:
  - sonarqubes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatgov.io
  resources:
  - sonarqubes/status
  verbs:
  - get
