apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarqube-operator-system
namePrefix: sonarqube-operator-

bases:
- ../crd
- ../rbac
- ../manager

patchesJson6902:
- path: namespace_scope_patch_role.yaml
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: manager-role
- path: namespace_scope_patch_rolebinding.yaml
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRoleBinding
    name: manager-rolebinding

patchesStrategicMerge:
- namespace_scope_patch.yaml
