apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: sonarqube-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Deploys and manages SonarQube and dependent database.
  displayName: SonarQube Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - redhatgov
  - sonarqube
  - devsecops
  links:
  - name: SonarQube
    url: https://www.sonarqube.org
  - name: SonarQube Operator
    url: https://github.com/jharmison-redhat/sonarqube-operator
  maintainers:
  - email: jharmison@redhat.com
    name: James Harmison
  maturity: alpha
  provider:
    name: RedHatGov
    url: redhatgov.io
  version: 0.0.0
